pr: none
trigger: none

jobs:

  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'

    strategy:
      matrix:
        fedora33:
          image: symless/synergy-core:fedora30
          packager: rpm
          name: fedora30

    container: $[ variables['image'] ]

    steps:
      - template: CI/checkout.yml
      - template: CI/Linux/linux-build.yml
